name: JakePlugin
version: '1.0-SNAPSHOT'
main: io.github.jakeslye.jakePlugin.JakePlugin
api-version: '1.21'
depend: [ProtocolLib]

commands:
  afk:
    description: lets players go afk
  restartlater:
    description: restarts in 2 minutes
    permission: bukkit.command.op
  settag:
    description: sets tag
    permission: bukkit.command.op